// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-laaDdLcOYbvdj9gnFooFacB6fxXwqY',
    appId: '1:812397989389:web:a6195943db90634433cf44',
    messagingSenderId: '812397989389',
    projectId: 'loginapp2025-9f434',
    authDomain: 'loginapp2025-9f434.firebaseapp.com',
    storageBucket: 'loginapp2025-9f434.firebasestorage.app',
    measurementId: 'G-DR5FGXQ46S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtWVWa3LDKFCSBOQkI2FoSV6LL7Ls3NU',
    appId: '1:812397989389:android:7bac375d9810f24a33cf44',
    messagingSenderId: '812397989389',
    projectId: 'loginapp2025-9f434',
    storageBucket: 'loginapp2025-9f434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksOAHzxkFMe_Zapus6uLBeOgj5DnbAU4',
    appId: '1:812397989389:ios:f5a7aec48ef90d8033cf44',
    messagingSenderId: '812397989389',
    projectId: 'loginapp2025-9f434',
    storageBucket: 'loginapp2025-9f434.firebasestorage.app',
    iosBundleId: 'com.example.loginApp2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDksOAHzxkFMe_Zapus6uLBeOgj5DnbAU4',
    appId: '1:812397989389:ios:f5a7aec48ef90d8033cf44',
    messagingSenderId: '812397989389',
    projectId: 'loginapp2025-9f434',
    storageBucket: 'loginapp2025-9f434.firebasestorage.app',
    iosBundleId: 'com.example.loginApp2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH-laaDdLcOYbvdj9gnFooFacB6fxXwqY',
    appId: '1:812397989389:web:7a8223fcf79c95bb33cf44',
    messagingSenderId: '812397989389',
    projectId: 'loginapp2025-9f434',
    authDomain: 'loginapp2025-9f434.firebaseapp.com',
    storageBucket: 'loginapp2025-9f434.firebasestorage.app',
    measurementId: 'G-YT8MC1J3DW',
  );
}
